server:
    port: 6020
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
management:
    security:
        enabled: false        