server:
    port: 6040
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    zipkin:
        base-url: http://DC12985.biostime.com:6030
my:
    message: i am zuul
zuul:
    routes:
        o2o: /o2o/**
        sns: /sns/**
